//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonoAndroidPullToRefresh
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_pulltorefresh_arrow = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int pull_to_refresh_header = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int pull_to_refresh_image = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int pull_to_refresh_progress = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int pull_to_refresh_text = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int pull_to_refresh_updated_at = 2131034116;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int pull_to_refresh_header = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int pulltorefreshlist = 2130903041;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int pull_to_refresh_pull_label = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int pull_to_refresh_refreshing_label = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int pull_to_refresh_release_label = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int pull_to_refresh_tap_label = 2130968580;
			
			private String()
			{
			}
		}
	}
}
